### ISSUE TITLE
Is old package broken?

### ISSUE THREAD

**Issue by mudlee** [ctimmerm/axios-mock-adapter#118]
hi.
Note that I'm not an expert front-end developer, but I have a problem with this module.
I use `"axios-mock-adapter": "^1.7.1",` in my package.json.

I had to remove node_modules and reinstall the dependencies and after that some of my tests are failing. I did not change the version though. in the node_modules/axios-mock-adapter/package.json I see this line: `"_id": "axios-mock-adapter@1.14.0",` which was `"_id": "axios-mock-adapter@1.12.0",` before the node_modules reinstall.

The actual problem is that when I run this snippet, the url does not called second time somewhy. 
`
mock
        .onGet(/URL/)
        .replyOnce(() => [
          200,
          revealableIdeas.slice(0, 5),
          {
            'x-next-page': '1',
            'x-current-page': '0',
            'x-prev-page': '-1',
            'x-last-page': '1'
          }
        ])
        .onGet(/URL/)
        .replyOnce(() => [
          200,
          revealableIdeas.slice(5, 10),
          {
            'x-next-page': '-1',
            'x-current-page': '1',
            'x-prev-page': '1',
            'x-last-page': '1'
          }
        ]);
`

Can I see somewhere the changes between 1.12 and 1.14?

**Comment by evanbattaglia** [comment]
Hi,
We were having the same problem and I tracked it down to this PR / commit.

https://github.com/ctimmerm/axios-mock-adapter/pull/115/files
https://github.com/ctimmerm/axios-mock-adapter/pull/115/commits/4e1e469326e848a1f41be1e4278eda1327c928fc

The problem is that the `utils.purgeIfReplyOnce(mockAdapter, handler);` was moved to under the `if` statement ` } else if (!(handler[3] instanceof Function)) {`. `handler[3]` is the first argument to `replyOnce`. Thus, if we pass replyOnce in as a function, like above (`replyOnce((config) => { ... }`), it will not run `utils.purgeIfReplyOnce`. It still works correctly if we we run `replyOnce(value)` with a non-function, as `purgeIfReplyOnce` is still called.

Let me know if you need a PR to fix the issue. I'm not sure why the call was moved, maybe we can just add it above where it was (e.g. right above `if (handler.length === 2) {`)

```
if (handler.length === 7) {
  utils.purgeIfReplyOnce(mockAdapter, handler);
}
```

**Comment by ctimmerm** [comment]
A fix has been made an a new version has been published.

**Comment by evanbattaglia** [comment]
Wow, thanks for the quick turnaround!
