### ISSUE TITLE
302 redirects 

### ISSUE THREAD

**Issue by AlecTroemel** [ctimmerm/axios-mock-adapter#145]
It would be useful to be able to reply with a 302 in my mocks

```
mock
    .onGet('/first')
    .reply(302, null, { location: '/second' });
```

**Comment by kodie** [comment]
I was able to accomplish this by doing the following:

```javascript
mock
  .onGet('/first')
  .reply(async config => {
    const redirectResponse = await axios.get('/second')
    return [302, redirectResponse]
  })
```

**Comment by kodie** [comment]
However that doesn't help if you need the response URL to change.

It would be really nice if you could return an axios method and have it automatically respond with a 301:
```javascript
mock
  .onGet('/first')
  .reply(config => {
    return axios.get('/second')
  })
```

**Comment by kodie** [comment]
After some testing and research, to my understanding it seems like the browser always handles redirects thus your axios response should never have a 301-303 status code.

For example if I have the file `redirect.php` that contains:
```php
<?php headers('Location: https://google.com'); exit(); ?>
```

and then do:
```javascript
axis.get('http://localhost:3000/redirect.php')
```

I get a `200` response status with the contents of the Google homepage.

Therefore, I have submitted Pull Request #162 which allows us to return an axios request from a reply callback function so that we may mock redirects.
