### ISSUE TITLE
Can Not Mocking a request with  route params

### ISSUE THREAD

**Issue by Gopaljeepurwar** [ctimmerm/axios-mock-adapter#82]
Can Not Mocking a request with route params
like this:

`mock.onGet('/api/colleges/:collegeId/branches/:branchesId').reply(200);`

**Comment by zakharov-dy** [comment]
@Gopaljeepurwar use a regex:
`mock.onGet(/\/api\/colleges\/.+\/branches\/.+/).reply(200);`

if you need route params values:
```
mock.onGet(/\/api\/colleges\/.+\/branches\/.+/).reply(config => {
    console.log(config.url); <- you url
    return [200];
  });
```

**Comment by franciscop-invast** [comment]
This is not the same; for instance `/whatever/api/colleges/20/branches/10` will also be matched (note here it starts by `/whatever`. In this situation is rather complex, but it can lead to errors in simpler cases:

```js
mock.onget(/\/notifications/)...
```

```js
axios.get('/user/20/notifications/')...
```

Regex is hard (and powerful!) by design, but this unfortunately means it's easy to shoot yourself in the foot. Would it be possible to integrate something like [path-to-regexp-wrap](https://github.com/teologov/path-to-regexp-wrap)? It would then make it trivial to write as the OP suggested:

```js
axios.onget('/api/colleges/:collegeId/branches/:branchesId')
```
