### ISSUE TITLE
Feature MockAdapter with random delayResponse 

### ISSUE THREAD

**Issue by tjunussov** [ctimmerm/axios-mock-adapter#86]
In order to achieve random timing of responses
Is it possible to pass function to delayResponse not staticaly?
`let mock = new MockAdapter(axios,{delayResponse:500})`
but 
```
let mock = new MockAdapter(axios,{delayResponse: function(){
  return 100+Math.round(Math.random()*1000) // from 100-1100ms
}})
```

**Comment by ctimmerm** [comment]
You can return a promise in the function you pass to onGet/onPost/... and resolve the promise in a setTimeout that has a random timeout.

However, in my opinion it's better to have a separate test that tests with a very short delay and then one with a long delay, rather than introducing randomness in your test cases.
